# Generated by Django 4.1 on 2022-08-25 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usertoken_alter_account_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='phone_number',
            new_name='mobile',
        ),
    ]
