# Generated by Django 4.1 on 2022-08-25 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_phone_number_account_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='mobile',
            new_name='phone_number',
        ),
    ]
